name: Build and deploy

on:
  push:
    branches: [master]

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install dependencies
        run: pip install --upgrade -r requirements.txt
      - name: build website
        run: python build.py
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/
          force_orphan: true
